# Generated by Django 5.2.4 on 2025-07-27 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time_to_start",
                    models.TimeField(
                        help_text="Укажите время выполнения привычки", verbose_name="Время выполнения привычки"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет из себя привычка",
                        max_length=120,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите подробнее о действии, которое представляет из себя привычка",
                        null=True,
                        verbose_name="Описание действия",
                    ),
                ),
                ("is_pleasant_habit", models.BooleanField()),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 день"),
                            (2, "2 дня"),
                            (3, "3 дня"),
                            (4, "4 дня"),
                            (5, "5 дней"),
                            (6, "6 дней"),
                        ],
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях",
                        verbose_name="Периодичность в днях",
                    ),
                ),
                ("award", models.TextField(blank=True, null=True, verbose_name="Вознаграждение")),
                (
                    "duration",
                    models.TimeField(
                        help_text="Укажите время выполнения привычки", verbose_name="Время выполнения привычки"
                    ),
                ),
                ("is_public", models.BooleanField()),
                (
                    "related_habit",
                    models.ForeignKey(
                        help_text="Укажите привычку, связанную с полезной привычкой",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_habits",
                        to="atomic_habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
