# Generated by Django 5.2.4 on 2025-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant_habit",
            field=models.BooleanField(verbose_name="Приятная привычка"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(verbose_name="Опубликовать"),
        ),
    ]
