# Generated by Django 5.2.4 on 2025-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0002_alter_habit_is_pleasant_habit_alter_habit_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_completed",
            field=models.DateField(blank=True, null=True, verbose_name="Время последнего выполнения привычки"),
        ),
    ]
