# Generated by Django 5.2.4 on 2025-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0003_habit_last_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Telegram chat ID"),
        ),
    ]
