# Generated by Django 5.2.4 on 2025-08-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0004_habit_tg_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="tg_chat_id",
        ),
    ]
