# Generated by Django 5.2.4 on 2025-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0005_remove_habit_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 день"),
                    (2, "2 дня"),
                    (3, "3 дня"),
                    (4, "4 дня"),
                    (5, "5 дней"),
                    (6, "6 дней"),
                    (7, "7 дней"),
                ],
                default=1,
                help_text="Укажите периодичность выполнения привычки в днях",
                verbose_name="Периодичность в днях",
            ),
        ),
    ]
